# Generated by Django 3.1.1 on 2023-03-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlistID', models.IntegerField()),
                ('username', models.TextField()),
                ('apartmentID', models.IntegerField()),
            ],
        ),
    ]
