# Generated by Django 3.1.1 on 2023-03-21 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='wishlistID',
        ),
    ]
