# Generated by Django 3.1.1 on 2023-03-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_remove_wishlist_wishlistid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('ApartmentID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('Image', models.ImageField(upload_to='apartment_images/')),
                ('Beds', models.IntegerField()),
                ('Bath', models.BooleanField()),
                ('Rent', models.IntegerField()),
                ('Area', models.IntegerField()),
                ('Furnished', models.BooleanField()),
                ('Parking', models.BooleanField()),
                ('Pool', models.BooleanField()),
                ('Gatedcommunity', models.BooleanField()),
                ('Patio', models.BooleanField()),
                ('Garden', models.BooleanField()),
                ('HardwoodFloors', models.BooleanField()),
                ('Gym', models.BooleanField()),
                ('DisabilityAccess', models.BooleanField()),
                ('Kidfriendly', models.BooleanField()),
                ('Washerdryer', models.BooleanField()),
                ('Dishwasher', models.BooleanField()),
                ('Radius', models.IntegerField()),
            ],
        ),
    ]
