# Generated by Django 3.1.1 on 2023-04-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='Bath',
            field=models.IntegerField(),
        ),
    ]
